services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/API
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ayds123
      POSTGRES_PASSWORD: ayds123
      POSTGRES_DB: proyecto_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
